#define DEFAULT_SCREEN_WIDTH 800
#define DEFAULT_SCREEN_HEIGHT 600
#define ASPECT_RATIO ((float) DEFAULT_SCREEN_WIDTH / (float) DEFAULT_SCREEN_HEIGHT)

#define NUM_SECTIONS_CIRCLE 60

#define MAX_VERTICES 100
